In [2]:
# import libraries
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from google.colab import files


In [3]:
uploaded=files.upload()

Saving ML Final football.xlsx to ML Final football.xlsx


In [4]:
# read file using pandas
df=pd.read_excel('ML Final football.xlsx') 

In [5]:
# View first 5 data points
df.head()

Position  Crossing  ...  SlidingTackle  International Reputation
0      LCB      40.0  ...             82                         1
1       RW      83.0  ...             33                         1
2      LCB      40.0  ...             82                         1
3       ST      56.0  ...             24                         1
4       LS      61.0  ...             41                         1

[5 rows x 30 columns]

In [6]:
# check whether there are any null values
df.isna().sum()

Position                    0
Crossing                    0
Finishing                   0
HeadingAccuracy             0
ShortPassing                0
Volleys                     0
Dribbling                   0
Curve                       0
FKAccuracy                  0
LongPassing                 0
BallControl                 0
SprintSpeed                 0
Agility                     0
Reactions                   0
Balance                     0
ShotPower                   0
Jumping                     0
Stamina                     0
Strength                    0
LongShots                   0
Aggression                  0
Interceptions               0
Positioning                 0
Vision                      0
Penalties                   0
Composure                   0
Marking                     0
StandingTackle              0
SlidingTackle               0
International Reputation    0
dtype: int64

In [6]:
df.drop(labels='Unnamed: 0',axis=1,inplace=True) # Drop Unnamed column

In [7]:
import warnings
warnings.filterwarnings('ignore')

In [8]:
# Information about data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18147 entries, 0 to 18146
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Position                  18147 non-null  object 
 1   Crossing                  18147 non-null  float64
 2   Finishing                 18147 non-null  float64
 3   HeadingAccuracy           18147 non-null  float64
 4   ShortPassing              18147 non-null  float64
 5   Volleys                   18147 non-null  float64
 6   Dribbling                 18147 non-null  float64
 7   Curve                     18147 non-null  float64
 8   FKAccuracy                18147 non-null  float64
 9   LongPassing               18147 non-null  float64
 10  BallControl               18147 non-null  float64
 11  SprintSpeed               18147 non-null  float64
 12  Agility                   18147 non-null  float64
 13  Reactions                 18147 non-null  float64
 14  Balanc

In [9]:
df

Position   Crossing  ...  SlidingTackle  International Reputation
0          LCB  40.000000  ...             82                         1
1           RW  83.000000  ...             33                         1
2          LCB  40.000000  ...             82                         1
3           ST  56.000000  ...             24                         1
4           LS  61.000000  ...             41                         1
...        ...        ...  ...            ...                       ...
18142       ST  84.000000  ...             23                         5
18143       LW  79.000000  ...             33                         5
18144       RS  77.000000  ...             38                         5
18145       GK  68.666667  ...             11                         5
18146       RS  73.000000  ...             24                         5

[18147 rows x 30 columns]

In [22]:
# Decision Tree Classification
X=df.iloc[:,1:-1].values
Y=df.iloc[:,-1].values

In [23]:
X,Y

(array([[40.        , 42.        , 80.        , ..., 92.        ,
         88.        , 82.        ],
        [83.        , 74.        , 64.        , ..., 24.        ,
         35.        , 33.        ],
        [40.        , 38.        , 83.        , ..., 85.        ,
         87.        , 82.        ],
        ...,
        [77.        , 93.        , 77.        , ..., 35.08333333,
         45.        , 38.        ],
        [68.66666667, 78.        , 67.66666667, ..., 32.5       ,
         10.        , 11.        ],
        [73.        , 86.        , 83.        , ..., 28.        ,
         37.        , 24.        ]]), array([1, 1, 1, ..., 5, 5, 5]))

In [24]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test =train_test_split(X, Y, test_size = 0.30, random_state = 0)
print(X_train)
print(Y_train)
print(X_test)
print(Y_test)

[[65.         47.         47.         ... 59.         57.
  54.        ]
 [62.         56.         49.         ... 58.         62.
  60.        ]
 [20.         11.         20.         ... 20.         20.
  19.        ]
 ...
 [24.         19.         59.         ... 66.         67.
  65.        ]
 [63.         24.         50.         ... 55.         61.
  58.        ]
 [11.         12.         51.40393462 ... 18.         14.
  10.        ]]
[1 1 1 ... 1 1 1]
[[49. 45. 33. ... 27. 23. 24.]
 [57. 31. 65. ... 52. 68. 69.]
 [43. 42. 47. ... 46. 48. 42.]
 ...
 [54. 57. 40. ... 47. 50. 45.]
 [55. 61. 43. ... 39. 27. 29.]
 [33. 67. 64. ... 36. 17. 10.]]
[1 1 1 ... 1 1 1]


In [25]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[ 0.81495432  0.07191832 -0.66741033 ...  0.58329581  0.41974934
   0.38236359]
 [ 0.64979125  0.53304932 -0.51167516 ...  0.53290061  0.65127058
   0.66488797]
 [-1.66249175 -1.77260565 -2.76983515 ... -1.38211723 -1.29350778
  -1.26569526]
 ...
 [-1.44227432 -1.36271144  0.2670007  ...  0.93606226  0.88279181
   0.90032495]
 [ 0.70484561 -1.10652755 -0.43380757 ...  0.38171499  0.60496633
   0.57071317]
 [-2.15798096 -1.72136888 -0.32448657 ... -1.48290764 -1.57133326
  -1.68948182]]
[[-0.06591539 -0.03055523 -1.75755653 ... -1.02935078 -1.15459504
  -1.03025828]
 [ 0.37451946 -0.74787011  0.73420621 ...  0.23052937  0.92909605
   1.08867453]
 [-0.39624153 -0.18426556 -0.66741033 ... -0.07184187  0.00301112
  -0.18268516]
 ...
 [ 0.20935639  0.58428609 -1.21248343 ... -0.02144666  0.09561962
  -0.04142297]
 [ 0.26441075  0.7892332  -0.97888068 ... -0.42460831 -0.96937805
  -0.7948213 ]
 [-0.94678511  1.09665386  0.65633863 ... -0.57579393 -1.43242052
  -1.68948182]]


In [27]:
# Training the Decision Tree Classification model on the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [34]:
# Predicting a new result
print(classifier.predict(sc.transform([[75,85,70,82,76,78,72,77,77,82,83,85,75,76,86,79,80,82,86,74,80,70,52,53,75,30,31,24]])))

[1]


In [35]:
# Predicting the Test set results
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))


[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [36]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[4826  126   18    1    0]
 [ 113  231   25    5    0]
 [  16   15   49    1    0]
 [   1    3    5    7    0]
 [   0    0    0    1    2]]


0.9393939393939394